createOrReplace

	model Model
		culture: en-US
		defaultPowerBIDataSourceVersion: powerBI_V3
		discourageImplicitMeasures
		sourceQueryCulture: en-US
		dataAccessOptions
			legacyRedirects
			returnErrorValuesAsNull

		table dim_customers
			lineageTag: 96463a11-7961-4b8a-8287-b0ec159b0f89

			column customer_key
				dataType: int64
				isHidden
				formatString: 0
				sourceProviderType: int
				lineageTag: 3cec1855-11aa-461b-988d-a374d4f8c417
				summarizeBy: none
				sourceColumn: customer_key

				changedProperty = IsHidden

				annotation SummarizationSetBy = Automatic

			column customer_id
				dataType: string
				sourceProviderType: nvarchar(65535)
				lineageTag: f83a37b4-2375-422f-a94c-56b43fff6111
				summarizeBy: none
				sourceColumn: customer_id

				annotation SummarizationSetBy = Automatic

			column customer_name
				dataType: string
				sourceProviderType: nvarchar(65535)
				lineageTag: bc267902-c483-48cc-ae9e-ebe9a5418555
				summarizeBy: none
				sourceColumn: customer_name

				annotation SummarizationSetBy = Automatic

			column segment
				dataType: string
				sourceProviderType: nvarchar(65535)
				lineageTag: 2c322579-90e9-4c9e-9950-bb3893610a9a
				summarizeBy: none
				sourceColumn: segment

				annotation SummarizationSetBy = Automatic

			column first_order_date
				dataType: dateTime
				formatString: Long Date
				sourceProviderType: date
				lineageTag: 0ee45654-ee78-4f34-979e-7dbc4b2fcddc
				summarizeBy: none
				sourceColumn: first_order_date

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Date

			column last_order_date
				dataType: dateTime
				formatString: Long Date
				sourceProviderType: date
				lineageTag: 17a527c2-9631-4709-85c9-0f6a2fcfd129
				summarizeBy: none
				sourceColumn: last_order_date

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Date

			column total_orders
				dataType: int64
				formatString: 0
				sourceProviderType: bigint
				lineageTag: 8691197c-a1c7-4c52-8270-ada671056658
				summarizeBy: none
				sourceColumn: total_orders

				annotation SummarizationSetBy = Automatic

			column customer_status
				dataType: string
				sourceProviderType: nvarchar(65535)
				lineageTag: ef809a5f-3a64-4d07-9531-2584ef904c78
				summarizeBy: none
				sourceColumn: customer_status

				annotation SummarizationSetBy = Automatic

			partition dim_customers = m
				mode: import
				source =
						let
						    Source = DatabricksMultiCloud.Catalogs("dbc-a00e21c3-4879.cloud.databricks.com", "/sql/1.0/warehouses/241bd8c1ba6b3df1", [Catalog = "", Database = ""]),
						    gold_dev_Database = Source{[Name="gold_dev",Kind="Database"]}[Data],
						    global_mart_retail_Schema = gold_dev_Database{[Name="global_mart_retail",Kind="Schema"]}[Data],
						    dim_customers_Table = global_mart_retail_Schema{[Name="dim_customers",Kind="Table"]}[Data],
						    #"Removed Other Columns" = Table.SelectColumns(dim_customers_Table,{"customer_key", "customer_id", "customer_name", "segment", "first_order_date", "last_order_date", "total_orders", "customer_status"})
						in
						    #"Removed Other Columns"

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		table dim_date
			lineageTag: 4719ad01-0ed7-46c1-ac1b-42cdeda790d6

			column date
				dataType: dateTime
				formatString: Short Date
				sourceProviderType: date
				lineageTag: 971b0dcf-7e2e-4008-9343-e333b40c7efc
				summarizeBy: none
				sourceColumn: date

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Date

			column date_key
				dataType: int64
				isHidden
				formatString: 0
				sourceProviderType: int
				lineageTag: 2e25354b-503c-4e3b-ae32-4e5a53ac7d12
				summarizeBy: none
				sourceColumn: date_key

				changedProperty = IsHidden

				annotation SummarizationSetBy = Automatic

			column year
				dataType: int64
				formatString: 0
				sourceProviderType: int
				lineageTag: 6c98e949-74b5-4cda-b60c-1215a33c884f
				summarizeBy: none
				sourceColumn: year

				annotation SummarizationSetBy = Automatic

			column quarter
				dataType: int64
				formatString: 0
				sourceProviderType: int
				lineageTag: 58ecf080-3cea-4708-99e1-da68cb547825
				summarizeBy: none
				sourceColumn: quarter

				annotation SummarizationSetBy = Automatic

			column quarter_name
				dataType: string
				sourceProviderType: nvarchar(65535)
				lineageTag: 5f796d7f-2f6e-4ec7-8118-c5a9dd3b67f9
				summarizeBy: none
				sourceColumn: quarter_name

				annotation SummarizationSetBy = Automatic

			column month
				dataType: int64
				formatString: 0
				sourceProviderType: int
				lineageTag: 1b29f6aa-1ece-4d5f-b9d4-36c782e9e1c9
				summarizeBy: none
				sourceColumn: month

				annotation SummarizationSetBy = Automatic

			column month_name
				dataType: string
				sourceProviderType: nvarchar(65535)
				lineageTag: 1428d020-b49c-40f7-961f-91e036b9d2a0
				summarizeBy: none
				sourceColumn: month_name

				annotation SummarizationSetBy = Automatic

			column month_short
				dataType: string
				sourceProviderType: nvarchar(65535)
				lineageTag: c8410d6d-2461-450e-bdf9-64d013689ce5
				summarizeBy: none
				sourceColumn: month_short

				annotation SummarizationSetBy = Automatic

			column week_of_year
				dataType: int64
				formatString: 0
				sourceProviderType: int
				lineageTag: 196d490f-8f93-4791-8af7-4fcba88d3042
				summarizeBy: none
				sourceColumn: week_of_year

				annotation SummarizationSetBy = Automatic

			column day
				dataType: int64
				formatString: 0
				sourceProviderType: int
				lineageTag: 5ed3a6c9-e1f3-4f31-ab0a-fc140b42cf5b
				summarizeBy: none
				sourceColumn: day

				annotation SummarizationSetBy = Automatic

			column day_name
				dataType: string
				sourceProviderType: nvarchar(65535)
				lineageTag: d2fd1d6c-c3cb-4c62-a5b6-b61f6034f10c
				summarizeBy: none
				sourceColumn: day_name

				annotation SummarizationSetBy = Automatic

			column day_short
				dataType: string
				sourceProviderType: nvarchar(65535)
				lineageTag: 513e2c1f-8e54-4a07-b4d3-285ba25c15e1
				summarizeBy: none
				sourceColumn: day_short

				annotation SummarizationSetBy = Automatic

			column day_of_week
				dataType: int64
				formatString: 0
				sourceProviderType: int
				lineageTag: 1d21bac3-9c0e-4482-b2a7-4a68cae80283
				summarizeBy: none
				sourceColumn: day_of_week

				annotation SummarizationSetBy = Automatic

			column is_weekend
				dataType: boolean
				formatString: """TRUE"";""TRUE"";""FALSE"""
				sourceProviderType: bit
				lineageTag: e61778c2-09ea-4ecb-9190-d445e3d84a25
				summarizeBy: none
				sourceColumn: is_weekend

				annotation SummarizationSetBy = Automatic

			column current_week_offset
				dataType: double
				sourceProviderType: double
				lineageTag: 240768b6-0d8b-4608-beb9-f0617e6aa4dc
				summarizeBy: none
				sourceColumn: current_week_offset

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column current_month_offset
				dataType: int64
				formatString: 0
				sourceProviderType: bigint
				lineageTag: 5f600f22-c686-4495-959b-5f216038a50c
				summarizeBy: none
				sourceColumn: current_month_offset

				annotation SummarizationSetBy = Automatic

			column current_year_offset
				dataType: int64
				formatString: 0
				sourceProviderType: int
				lineageTag: 29a548a6-d771-4e1b-9c11-3b229d3e6ed4
				summarizeBy: none
				sourceColumn: current_year_offset

				annotation SummarizationSetBy = Automatic

			column month_year
				dataType: string
				lineageTag: d4ea958e-cd69-4f53-a8ee-bd32aaac4bca
				summarizeBy: none
				sourceColumn: month_year
				sortByColumn: month_year_key

				changedProperty = SortByColumn

				annotation SummarizationSetBy = Automatic

			column month_year_key
				dataType: string
				lineageTag: 992ad4a6-339f-4358-b688-1240d2ec2aee
				summarizeBy: none
				sourceColumn: month_year_key

				annotation SummarizationSetBy = Automatic

			hierarchy Calendar

				level Year
					column: year

				level Quarter
					column: quarter_name

				level Month
					column: month_name

				level Date
					column: date

			partition dim_date = m
				mode: import
				source =
						let
						    Source = DatabricksMultiCloud.Catalogs("dbc-a00e21c3-4879.cloud.databricks.com", "/sql/1.0/warehouses/241bd8c1ba6b3df1", [Catalog = "", Database = ""]),
						    gold_dev_Database = Source{[Name="gold_dev",Kind="Database"]}[Data],
						    global_mart_retail_Schema = gold_dev_Database{[Name="global_mart_retail",Kind="Schema"]}[Data],
						    dim_date_Table = global_mart_retail_Schema{[Name="dim_date",Kind="Table"]}[Data]
						in
						    dim_date_Table

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		table dim_geography
			lineageTag: dcc62d9b-6d85-4cfd-9a9a-adf36dfbfd61

			column geography_key
				dataType: int64
				isHidden
				formatString: 0
				sourceProviderType: int
				lineageTag: 2ef87966-40e2-4235-9769-3a330cdfaa81
				summarizeBy: none
				sourceColumn: geography_key

				changedProperty = IsHidden

				annotation SummarizationSetBy = Automatic

			column country
				dataType: string
				sourceProviderType: nvarchar(65535)
				lineageTag: d9afdcee-9aa2-4706-aea3-c83dee9ba540
				summarizeBy: none
				sourceColumn: country

				annotation SummarizationSetBy = Automatic

			column region
				dataType: string
				sourceProviderType: nvarchar(65535)
				lineageTag: 2ed5ebc8-9c4a-4b40-b2a0-65a0648b4b7e
				summarizeBy: none
				sourceColumn: region

				annotation SummarizationSetBy = Automatic

			column state
				dataType: string
				sourceProviderType: nvarchar(65535)
				lineageTag: 658b32c5-6b60-41e4-948b-f902c35a61d4
				summarizeBy: none
				sourceColumn: state

				annotation SummarizationSetBy = Automatic

			column city
				dataType: string
				sourceProviderType: nvarchar(65535)
				lineageTag: a278916d-dda1-4e8a-a9a9-0218a0dc9ba0
				summarizeBy: none
				sourceColumn: city

				annotation SummarizationSetBy = Automatic

			column postal_code
				dataType: string
				sourceProviderType: nvarchar(65535)
				lineageTag: 0edab540-9b6c-4e36-ac6d-8c2a35bc77a7
				summarizeBy: none
				sourceColumn: postal_code

				annotation SummarizationSetBy = Automatic

			hierarchy Geography

				level Country
					column: country

				level Region
					column: region

				level State
					column: state

				level City
					column: city

			partition dim_geography = m
				mode: import
				source =
						let
						    Source = DatabricksMultiCloud.Catalogs("dbc-a00e21c3-4879.cloud.databricks.com", "/sql/1.0/warehouses/241bd8c1ba6b3df1", [Catalog = "", Database = ""]),
						    gold_dev_Database = Source{[Name="gold_dev",Kind="Database"]}[Data],
						    global_mart_retail_Schema = gold_dev_Database{[Name="global_mart_retail",Kind="Schema"]}[Data],
						    dim_geography_Table = global_mart_retail_Schema{[Name="dim_geography",Kind="Table"]}[Data],
						    #"Removed Other Columns" = Table.SelectColumns(dim_geography_Table,{"geography_key", "country", "region", "state", "city", "postal_code"})
						in
						    #"Removed Other Columns"

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		table dim_products
			lineageTag: 9e76e619-a476-45a0-ad90-5dbcd84edb8f

			column product_key
				dataType: int64
				isHidden
				formatString: 0
				sourceProviderType: int
				lineageTag: 463893ce-91cd-4706-85c7-0859086c9496
				summarizeBy: none
				sourceColumn: product_key

				changedProperty = IsHidden

				annotation SummarizationSetBy = Automatic

			column product_id
				dataType: string
				sourceProviderType: nvarchar(65535)
				lineageTag: 4f66431f-adc5-4809-8514-41d9b8a0a62f
				summarizeBy: none
				sourceColumn: product_id

				annotation SummarizationSetBy = Automatic

			column product_name
				dataType: string
				sourceProviderType: nvarchar(65535)
				lineageTag: 9f2f1a84-0ac5-4e1d-90ef-88b172f58655
				summarizeBy: none
				sourceColumn: product_name

				annotation SummarizationSetBy = Automatic

			column category
				dataType: string
				sourceProviderType: nvarchar(65535)
				lineageTag: 81e67030-0558-4475-b2d2-edfc77b16474
				summarizeBy: none
				sourceColumn: category

				annotation SummarizationSetBy = Automatic

			column sub_category
				dataType: string
				sourceProviderType: nvarchar(65535)
				lineageTag: 4ba2f65a-b57b-4dc4-9db7-45713a037ebd
				summarizeBy: none
				sourceColumn: sub_category

				annotation SummarizationSetBy = Automatic

			hierarchy Product

				level Category
					column: category

				level 'Sub Category'
					column: sub_category

				level 'Product Name'
					column: product_name

			partition dim_products = m
				mode: import
				source =
						let
						    Source = DatabricksMultiCloud.Catalogs("dbc-a00e21c3-4879.cloud.databricks.com", "/sql/1.0/warehouses/241bd8c1ba6b3df1", [Catalog = "", Database = ""]),
						    gold_dev_Database = Source{[Name="gold_dev",Kind="Database"]}[Data],
						    global_mart_retail_Schema = gold_dev_Database{[Name="global_mart_retail",Kind="Schema"]}[Data],
						    dim_products_Table = global_mart_retail_Schema{[Name="dim_products",Kind="Table"]}[Data],
						    #"Removed Other Columns" = Table.SelectColumns(dim_products_Table,{"product_key", "product_id", "product_name", "category", "sub_category"})
						in
						    #"Removed Other Columns"

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		table fact_sales
			lineageTag: 2733d3ce-107c-4505-aea1-233e558f2390

			column order_line_id
				dataType: int64
				isHidden
				formatString: 0
				sourceProviderType: int
				lineageTag: 4315c931-be29-456e-b76b-38e8a8701739
				summarizeBy: sum
				sourceColumn: order_line_id

				changedProperty = IsHidden

				annotation SummarizationSetBy = Automatic

			column customer_key
				dataType: int64
				isHidden
				formatString: 0
				sourceProviderType: int
				lineageTag: 51f3f0a1-43c7-4d55-aa3e-051d548cf9cb
				summarizeBy: none
				sourceColumn: customer_key

				changedProperty = IsHidden

				annotation SummarizationSetBy = Automatic

			column product_key
				dataType: int64
				isHidden
				formatString: 0
				sourceProviderType: int
				lineageTag: ab017569-f278-4651-8ef3-d9e043206573
				summarizeBy: none
				sourceColumn: product_key

				changedProperty = IsHidden

				annotation SummarizationSetBy = Automatic

			column geography_key
				dataType: int64
				isHidden
				formatString: 0
				sourceProviderType: int
				lineageTag: 59b00e84-ff99-47c9-b04b-cc38bc5b3bee
				summarizeBy: none
				sourceColumn: geography_key

				changedProperty = IsHidden

				annotation SummarizationSetBy = Automatic

			column order_date_key
				dataType: int64
				isHidden
				formatString: 0
				sourceProviderType: int
				lineageTag: 43367755-f0a8-4387-a06f-e3d6c46e2910
				summarizeBy: none
				sourceColumn: order_date_key

				changedProperty = IsHidden

				annotation SummarizationSetBy = Automatic

			column ship_date_key
				dataType: int64
				isHidden
				formatString: 0
				sourceProviderType: int
				lineageTag: 38a5083d-72ea-4295-aa28-1b8be877f002
				summarizeBy: sum
				sourceColumn: ship_date_key

				changedProperty = IsHidden

				annotation SummarizationSetBy = Automatic

			column order_date
				dataType: dateTime
				formatString: Short Date
				sourceProviderType: date
				lineageTag: b3ce4276-6154-4f16-8506-e9792793cd3e
				summarizeBy: none
				sourceColumn: order_date

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Date

			column ship_date
				dataType: dateTime
				formatString: Short Date
				sourceProviderType: date
				lineageTag: 2ad1dca7-b023-49e8-a7b5-b65481a5dbae
				summarizeBy: none
				sourceColumn: ship_date

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Date

			column order_id
				dataType: string
				sourceProviderType: nvarchar(65535)
				lineageTag: c4a8acb4-4cbb-46b6-856c-9bf1f2ac00c4
				summarizeBy: none
				sourceColumn: order_id

				annotation SummarizationSetBy = Automatic

			column ship_mode
				dataType: string
				sourceProviderType: nvarchar(65535)
				lineageTag: 2b3ba0b6-f051-4fa6-b52d-401829476ae9
				summarizeBy: none
				sourceColumn: ship_mode

				annotation SummarizationSetBy = Automatic

			column sales
				dataType: double
				sourceProviderType: double
				lineageTag: 853bea3c-a367-4d8a-a415-524ba99dd3dd
				summarizeBy: sum
				sourceColumn: sales

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column quantity
				dataType: int64
				formatString: 0
				sourceProviderType: int
				lineageTag: 4f6d5b82-4dce-4da0-b219-226bd3571542
				summarizeBy: sum
				sourceColumn: quantity

				annotation SummarizationSetBy = Automatic

			column discount
				dataType: double
				sourceProviderType: double
				lineageTag: c97dbc34-8f56-438f-9fa5-f36a23b389dc
				summarizeBy: sum
				sourceColumn: discount

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column profit
				dataType: double
				sourceProviderType: double
				lineageTag: 011992df-d6a6-4821-bf34-0d0b323a6662
				summarizeBy: sum
				sourceColumn: profit

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column unit_price
				dataType: double
				sourceProviderType: double
				lineageTag: 60f8dcd9-30bf-4603-b46d-bea1bd459150
				summarizeBy: sum
				sourceColumn: unit_price

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column profit_per_unit
				dataType: double
				sourceProviderType: double
				lineageTag: b8f163b0-e591-4bad-b9ec-bf941eba44f5
				summarizeBy: sum
				sourceColumn: profit_per_unit

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column profit_margin
				dataType: double
				sourceProviderType: double
				lineageTag: 7d30649d-77e9-42ab-8e3c-ddbe34d57610
				summarizeBy: sum
				sourceColumn: profit_margin

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column discount_bucket
				dataType: string
				sourceProviderType: nvarchar(65535)
				lineageTag: df04314b-51ef-4d93-8323-2de68ffd3761
				summarizeBy: none
				sourceColumn: discount_bucket

				annotation SummarizationSetBy = Automatic

			column delivery_days
				dataType: int64
				formatString: 0
				sourceProviderType: int
				lineageTag: 2f453ad5-2b9e-47f9-8969-5fb4d2d472a1
				summarizeBy: sum
				sourceColumn: delivery_days

				annotation SummarizationSetBy = Automatic

			column is_prime_delivery
				dataType: boolean
				formatString: """TRUE"";""TRUE"";""FALSE"""
				sourceProviderType: bit
				lineageTag: 18a17007-a3ab-4def-bf54-19c3f447b388
				summarizeBy: none
				sourceColumn: is_prime_delivery

				annotation SummarizationSetBy = Automatic

			column is_profitable
				dataType: boolean
				formatString: """TRUE"";""TRUE"";""FALSE"""
				sourceProviderType: bit
				lineageTag: c5eaf357-ab66-4baf-bf0d-f00c79b302c8
				summarizeBy: none
				sourceColumn: is_profitable

				annotation SummarizationSetBy = Automatic

			column order_size
				dataType: string
				sourceProviderType: nvarchar(65535)
				lineageTag: 97da56f8-25a7-4512-96fb-13e1c9739730
				summarizeBy: none
				sourceColumn: order_size

				annotation SummarizationSetBy = Automatic

			column transaction_type
				dataType: string
				sourceProviderType: nvarchar(65535)
				lineageTag: 6941effd-12d3-4f08-8891-aafce17aaf81
				summarizeBy: none
				sourceColumn: transaction_type

				annotation SummarizationSetBy = Automatic

			partition fact_sales = m
				mode: import
				source =
						let
						    Source = DatabricksMultiCloud.Catalogs("dbc-a00e21c3-4879.cloud.databricks.com", "/sql/1.0/warehouses/241bd8c1ba6b3df1", [Catalog = "", Database = ""]),
						    gold_dev_Database = Source{[Name="gold_dev",Kind="Database"]}[Data],
						    global_mart_retail_Schema = gold_dev_Database{[Name="global_mart_retail",Kind="Schema"]}[Data],
						    fact_sales_Table = global_mart_retail_Schema{[Name="fact_sales",Kind="Table"]}[Data],
						    #"Removed Other Columns" = Table.SelectColumns(fact_sales_Table,{"order_line_id", "customer_key", "product_key", "geography_key", "order_date_key", "ship_date_key", "order_date", "ship_date", "order_id", "ship_mode", "sales", "quantity", "discount", "profit", "unit_price", "profit_per_unit", "profit_margin", "discount_bucket", "delivery_days", "is_prime_delivery", "is_profitable", "order_size", "transaction_type"})
						in
						    #"Removed Other Columns"

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		/// Centralized measure table for all business metrics
		table Metrics
			lineageTag: 2744cb1b-823c-459c-bd3d-d94ad8356cad

			/// Total revenue from all sales transactions
			measure 'Total Sales' = SUM(fact_sales[sales])
				formatString: $#,0.00
				displayFolder: Base Metrics
				lineageTag: ade27b32-9126-4900-ab4e-50b333012023

			/// Total units sold across all transactions
			measure 'Total Quantity' = SUM(fact_sales[quantity])
				formatString: #,0
				displayFolder: Base Metrics
				lineageTag: 19f25cb8-d3b9-4dd6-82f4-650e0220aed5

			/// Total profit from all sales transactions
			measure 'Total Profit' = SUM(fact_sales[profit])
				formatString: $#,0.00
				displayFolder: Base Metrics
				lineageTag: 91a2c471-81b4-4377-a437-c81ad93da86f

			/// Count of unique orders placed
			measure 'Total Orders' = DISTINCTCOUNT(fact_sales[order_id])
				formatString: #,0
				displayFolder: Base Metrics
				lineageTag: b558a07c-b6cf-4433-99ac-6c78b36b666f

			/// Total number of line items across all orders
			measure 'Total Order Lines' = COUNTROWS(fact_sales)
				formatString: #,0
				displayFolder: Base Metrics
				lineageTag: 3a9f248e-a074-4e60-9df5-75ef7953d3e4

			/// Count of unique customers who made purchases
			measure 'Unique Customers' = DISTINCTCOUNT(fact_sales[customer_key])
				formatString: #,0
				displayFolder: Base Metrics
				lineageTag: 685441b3-eb53-4d26-a389-778d158baafb

			/// Average revenue per order
			measure 'Avg Order Value' = DIVIDE([Total Sales], [Total Orders], 0)
				formatString: $#,0.00
				displayFolder: Averages
				lineageTag: 144395ea-97f5-4c38-966d-57b4c2e0f482

			/// Average revenue per unique customer
			measure 'Avg Sales Per Customer' = DIVIDE([Total Sales], [Unique Customers], 0)
				formatString: $#,0.00
				displayFolder: Averages
				lineageTag: 63926d3c-3252-4f75-819d-2d6161434c3a

			/// Average units sold per order
			measure 'Avg Quantity Per Order' = DIVIDE([Total Quantity], [Total Orders], 0)
				formatString: #,0.0
				displayFolder: Averages
				lineageTag: 1dbe1616-e7cb-489e-89a7-0e7ffd6a82c8

			/// Average price per unit sold
			measure 'Avg Unit Price' = DIVIDE([Total Sales], [Total Quantity], 0)
				formatString: $#,0.00
				displayFolder: Averages
				lineageTag: 127b3f9c-fc1b-4605-a03e-551770f30fe1

			/// Profit as percentage of sales revenue
			measure 'Profit Margin %' = DIVIDE([Total Profit], [Total Sales], 0)
				formatString: 0.00%
				displayFolder: Profitability
				lineageTag: 7772852b-9ed3-4e10-ac22-0a4f6d27fd65

			/// Ratio of profit to sales (same as profit margin)
			measure 'Profit Ratio' = DIVIDE([Total Profit], [Total Sales], 0)
				formatString: 0.00
				displayFolder: Profitability
				lineageTag: 0d112cac-f107-4b91-8cbd-a6debef7548e

			/// Total cost of goods sold
			measure 'Total Cost' = [Total Sales] - [Total Profit]
				formatString: $#,0.00
				displayFolder: Profitability
				lineageTag: 4459e7af-3e7a-48ba-9cac-b1d80fd9bc44

			/// Average profit earned per order
			measure 'Avg Profit Per Order' = DIVIDE([Total Profit], [Total Orders], 0)
				formatString: $#,0.00
				displayFolder: Profitability
				lineageTag: f35d9d27-f49e-4074-95db-329b1c595f6a

			/// Average profit per unique customer
			measure 'Avg Profit Per Customer' = DIVIDE([Total Profit], [Unique Customers], 0)
				formatString: $#,0.00
				displayFolder: Profitability
				lineageTag: 7b4b95ef-cd8b-413e-bbc3-7af896cec32d

			/// Year-to-date total sales
			measure 'Sales YTD' = TOTALYTD([Total Sales], dim_date[date])
				formatString: $#,0.00
				displayFolder: Time Intelligence\Sales
				lineageTag: f7cae092-10c9-4bf8-950c-46524a9f6756

			/// Prior year-to-date total sales
			measure 'Sales PYTD' = CALCULATE([Sales YTD], SAMEPERIODLASTYEAR(dim_date[date]))
				formatString: $#,0.00
				displayFolder: Time Intelligence\Sales
				lineageTag: d7ca8fa9-6deb-4eaf-8d5b-38fc97456d17

			/// Year-over-year sales growth amount
			measure 'Sales YoY Growth' = [Total Sales] - [Sales PY]
				formatString: $#,0.00
				displayFolder: Time Intelligence\Sales
				lineageTag: 2d1301be-8837-4822-b26d-6d569338c68c

			/// Year-over-year sales growth percentage
			measure 'Sales YoY Growth %' = DIVIDE([Sales YoY Growth], [Sales PY], 0)
				formatString: 0.00%
				displayFolder: Time Intelligence\Sales
				lineageTag: ee13a899-040d-47be-80e5-fa4461b25d57

			/// Total sales for same period last year
			measure 'Sales PY' = CALCULATE([Total Sales], SAMEPERIODLASTYEAR(dim_date[date]))
				formatString: $#,0.00
				displayFolder: Time Intelligence\Sales
				lineageTag: 5c8063c9-6135-4072-8de6-1cba40d5045f

			/// Month-to-date total sales
			measure 'Sales MTD' = TOTALMTD([Total Sales], dim_date[date])
				formatString: $#,0.00
				displayFolder: Time Intelligence\Sales
				lineageTag: 86ec10fc-22dd-4a41-b2a8-e679643a5efe

			/// Quarter-to-date total sales
			measure 'Sales QTD' = TOTALQTD([Total Sales], dim_date[date])
				formatString: $#,0.00
				displayFolder: Time Intelligence\Sales
				lineageTag: e268d4cd-54e9-451c-b53c-9cb94efdd74f

			/// Total sales for previous month
			measure 'Sales PM' = CALCULATE([Total Sales], PREVIOUSMONTH(dim_date[date]))
				formatString: $#,0.00
				displayFolder: Time Intelligence\Sales
				lineageTag: afcdbce0-a6a6-429f-a9c4-c7aadd2b5f92

			/// Month-over-month sales growth percentage
			measure 'Sales MoM Growth %' = DIVIDE([Total Sales] - [Sales PM], [Sales PM], 0)
				formatString: 0.00%
				displayFolder: Time Intelligence\Sales
				lineageTag: 9aef3ad9-684e-4bf6-8707-8d56b5ff21f3

			/// Year-to-date total profit
			measure 'Profit YTD' = TOTALYTD([Total Profit], dim_date[date])
				formatString: $#,0.00
				displayFolder: Time Intelligence\Profit
				lineageTag: c8f17ae6-d42e-4656-bfa2-b870b4332cf9

			/// Total profit for same period last year
			measure 'Profit PY' = CALCULATE([Total Profit], SAMEPERIODLASTYEAR(dim_date[date]))
				formatString: $#,0.00
				displayFolder: Time Intelligence\Profit
				lineageTag: 44d76b41-ea43-43e6-9122-0b007d2a4d79

			/// Year-over-year profit growth amount
			measure 'Profit YoY Growth' = [Total Profit] - [Profit PY]
				formatString: $#,0.00
				displayFolder: Time Intelligence\Profit
				lineageTag: 6be7c44d-8265-48fb-a724-476911d8d2de

			/// Year-over-year profit growth percentage
			measure 'Profit YoY Growth %' = DIVIDE([Profit YoY Growth], [Profit PY], 0)
				formatString: 0.00%
				displayFolder: Time Intelligence\Profit
				lineageTag: b289b3fa-d78b-4ed8-b504-aa76180aa031

			/// Month-to-date total profit
			measure 'Profit MTD' = TOTALMTD([Total Profit], dim_date[date])
				formatString: $#,0.00
				displayFolder: Time Intelligence\Profit
				lineageTag: 54389113-020d-48f3-8403-a16248c83cec

			/// Quarter-to-date total profit
			measure 'Profit QTD' = TOTALQTD([Total Profit], dim_date[date])
				formatString: $#,0.00
				displayFolder: Time Intelligence\Profit
				lineageTag: 76515c56-56e8-4542-9b6c-26f56c923989

			/// Year-to-date total orders
			measure 'Orders YTD' = TOTALYTD([Total Orders], dim_date[date])
				formatString: #,0
				displayFolder: Time Intelligence\Orders
				lineageTag: f36c02cc-8c29-4f83-b9f7-cc64bf71493b

			/// Total orders for same period last year
			measure 'Orders PY' = CALCULATE([Total Orders], SAMEPERIODLASTYEAR(dim_date[date]))
				formatString: #,0
				displayFolder: Time Intelligence\Orders
				lineageTag: ed97c859-93cd-4d4a-972c-2272cf654360

			/// Year-over-year orders growth percentage
			measure 'Orders YoY Growth %' = DIVIDE([Total Orders] - [Orders PY], [Orders PY], 0)
				formatString: 0.00%
				displayFolder: Time Intelligence\Orders
				lineageTag: 8c0b98ac-88fb-4a47-8ba4-619cef47c7ce

			/// Year-to-date unique customers
			measure 'Customers YTD' = CALCULATE([Unique Customers], DATESYTD(dim_date[date]))
				formatString: #,0
				displayFolder: Time Intelligence\Customers
				lineageTag: 2e4e513a-3905-4435-8cbc-2f6cb7fd217e

			/// Unique customers for same period last year
			measure 'Customers PY' = CALCULATE([Unique Customers], SAMEPERIODLASTYEAR(dim_date[date]))
				formatString: #,0
				displayFolder: Time Intelligence\Customers
				lineageTag: 78323b7e-d1e2-4cb7-ba16-20f1ce26a73d

			/// Year-over-year customer growth percentage
			measure 'Customers YoY Growth %' = DIVIDE([Unique Customers] - [Customers PY], [Customers PY], 0)
				formatString: 0.00%
				displayFolder: Time Intelligence\Customers
				lineageTag: fe4f6a4c-fb88-4d02-9f4f-b7f56aeb087c

			/// 3-month moving average of sales
			measure 'Sales 3M Moving Avg' = AVERAGEX(DATESINPERIOD(dim_date[date], LASTDATE(dim_date[date]), -3, MONTH), [Total Sales])
				formatString: $#,0.00
				displayFolder: Time Intelligence\Moving Averages
				lineageTag: 91aedd69-c20e-4197-8e9f-6732a650659e

			/// 6-month moving average of sales
			measure 'Sales 6M Moving Avg' = AVERAGEX(DATESINPERIOD(dim_date[date], LASTDATE(dim_date[date]), -6, MONTH), [Total Sales])
				formatString: $#,0.00
				displayFolder: Time Intelligence\Moving Averages
				lineageTag: b98f1232-d97b-4a90-8993-ba3b577c4b35

			/// Total discount amount given across all sales
			measure 'Total Discount Amount' = SUMX(fact_sales, fact_sales[quantity] * fact_sales[unit_price] * fact_sales[discount])
				formatString: $#,0.00
				displayFolder: Discounts
				lineageTag: 0a0c4b33-6b13-4cfc-9203-8d82356ef945

			/// Average discount percentage across all transactions
			measure 'Avg Discount %' = AVERAGE(fact_sales[discount])
				formatString: 0.00%
				displayFolder: Discounts
				lineageTag: 06d5fbf7-95b1-4f59-8502-a1efe5341e60

			/// Count of orders that included a discount
			measure 'Orders With Discount' = CALCULATE([Total Orders], fact_sales[discount] > 0)
				formatString: #,0
				displayFolder: Discounts
				lineageTag: 8f326297-25bb-482f-a9ac-4a2d5f15e12c

			/// Percentage of orders that received a discount
			measure 'Discount Rate %' = DIVIDE([Orders With Discount], [Total Orders], 0)
				formatString: 0.00%
				displayFolder: Discounts
				lineageTag: 367f47c2-76f2-4340-9b27-6ca9d92a034f

			/// Average number of days from order to delivery
			measure 'Avg Delivery Days' = AVERAGE(fact_sales[delivery_days])
				formatString: #,0.0
				displayFolder: Operations
				lineageTag: ed92c4a2-96f8-42cb-b963-ce7c3025a619

			/// Count of orders with prime delivery
			measure 'Orders Prime Delivery' = CALCULATE([Total Orders], fact_sales[is_prime_delivery] = TRUE)
				formatString: #,0
				displayFolder: Operations
				lineageTag: 6cde5996-d9f5-4ee9-8eaa-7a3e93eaf7e3

			column Metrics
				isHidden
				lineageTag: 124243c0-4ea8-402a-9fd7-f43216d29ec5
				isNameInferred
				sourceColumn: [Metrics]

			partition Metrics = calculated
				mode: import
				source = ROW("Metrics", 1)

		table 'Rolling Periods'
			lineageTag: 246090fa-b82d-4ef6-a147-481e65f67acd

			/// Dynamic time period calculations for rolling date ranges
			calculationGroup
				precedence: 10

				/// No time modification - shows current period values
				calculationItem 'Current Period' = SELECTEDMEASURE()

				/// Values for the last 7 days
				calculationItem 'Last 7 Days' = CALCULATE(SELECTEDMEASURE(), DATESINPERIOD(dim_date[date], LASTDATE(dim_date[date]), -7, DAY))

				/// Values for the last 30 days
				calculationItem 'Last 30 Days' = CALCULATE(SELECTEDMEASURE(), DATESINPERIOD(dim_date[date], LASTDATE(dim_date[date]), -30, DAY))

				/// Values for the last 90 days
				calculationItem 'Last 90 Days' = CALCULATE(SELECTEDMEASURE(), DATESINPERIOD(dim_date[date], LASTDATE(dim_date[date]), -90, DAY))

				/// Values for the last 12 months
				calculationItem 'Last 12 Months' = CALCULATE(SELECTEDMEASURE(), DATESINPERIOD(dim_date[date], LASTDATE(dim_date[date]), -12, MONTH))

			column 'Rolling Periods'
				dataType: string
				lineageTag: bca1b755-4dff-42ab-92e9-1e1756c0c271

			partition 'Partition_Rolling Periods' = calculationGroup

		table 'Time Comparison'
			lineageTag: e89a9704-da84-4c98-9cba-30032d9c2109

			/// Compare current period with previous periods
			calculationGroup
				precedence: 20

				/// Current period value
				calculationItem Current = SELECTEDMEASURE()

				/// Same period in previous year
				calculationItem 'Previous Year' = CALCULATE(SELECTEDMEASURE(), SAMEPERIODLASTYEAR(dim_date[date]))

				/// Previous month
				calculationItem 'Previous Month' = CALCULATE(SELECTEDMEASURE(), PREVIOUSMONTH(dim_date[date]))

				/// Previous quarter
				calculationItem 'Previous Quarter' = CALCULATE(SELECTEDMEASURE(), PREVIOUSQUARTER(dim_date[date]))

				/// Year-over-year change amount
				calculationItem 'YoY Change' = SELECTEDMEASURE() - CALCULATE(SELECTEDMEASURE(), SAMEPERIODLASTYEAR(dim_date[date]))

				/// Year-over-year change percentage
				calculationItem 'YoY Change %' =
						VAR CurrentValue = SELECTEDMEASURE()
						VAR PYValue = CALCULATE(SELECTEDMEASURE(), SAMEPERIODLASTYEAR(dim_date[date]))
						RETURN DIVIDE(CurrentValue - PYValue, PYValue, BLANK())

					formatStringDefinition = "0.00%"

			column 'Time Comparison'
				dataType: string
				lineageTag: 0ff62f1c-6b83-4af7-ae46-66d00009a93b

			partition 'Partition_Time Comparison' = calculationGroup

		table Period-to-Date
			lineageTag: 8dee095a-32d0-4b37-be3b-417ee5adbf27

			/// Period-to-date calculations (MTD, QTD, YTD)
			calculationGroup
				precedence: 15

				/// No period-to-date calculation applied
				calculationItem 'No Calculation' = SELECTEDMEASURE()

				/// Month-to-date cumulative total
				calculationItem MTD = CALCULATE(SELECTEDMEASURE(), DATESMTD(dim_date[date]))

				/// Quarter-to-date cumulative total
				calculationItem QTD = CALCULATE(SELECTEDMEASURE(), DATESQTD(dim_date[date]))

				/// Year-to-date cumulative total
				calculationItem YTD = CALCULATE(SELECTEDMEASURE(), DATESYTD(dim_date[date]))

				/// Prior year-to-date cumulative total
				calculationItem PYTD = CALCULATE(SELECTEDMEASURE(), DATESYTD(dim_date[date]), SAMEPERIODLASTYEAR(dim_date[date]))

			column Period-to-Date
				dataType: string
				lineageTag: 233ced5a-8cf8-4fb5-b662-e3766a8f236a

			partition Partition_Period-to-Date = calculationGroup

		relationship bdf10d50-4c82-f3f5-9a2e-ec45232797fc
			fromColumn: fact_sales.geography_key
			toColumn: dim_geography.geography_key

		relationship 31b1ceb5-974c-974b-2d00-3705e78bd349
			fromColumn: fact_sales.product_key
			toColumn: dim_products.product_key

		relationship cd2488d5-a178-76a4-8f7a-0e0d37c1346c
			fromColumn: fact_sales.customer_key
			toColumn: dim_customers.customer_key

		relationship 18c859ca-0763-fcd6-8cc2-1b4479c7ef2a
			fromColumn: fact_sales.order_date_key
			toColumn: dim_date.date_key

		relationship 5dbb5729-b1cb-377f-9c3d-09c069deac62
			isActive: false
			fromColumn: fact_sales.ship_date_key
			toColumn: dim_date.date_key

		cultureInfo en-US

			linguisticMetadata =
					{
					  "Version": "1.0.0",
					  "Language": "en-US"
					}
				contentType: json

		annotation __PBI_TimeIntelligenceEnabled = 0

		annotation PBI_QueryOrder = ["dim_customers","dim_date","dim_geography","dim_products","fact_sales"]

		annotation PBI_ProTooling = ["DevMode","MCP-PBIModeling"]

